---
  - name: Azure WebVM Playbook
    hosts: webservers
    become: true
    tasks:

    - name: Install docker.io
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Install python3
      apt:
        name: python3-pip
        state: present

    - name: Install docker python package
      pip:
        name: docker

    - name: Configure a DVWA container
      docker_container:
        name: dvwa_container
        image: cyberxsecurity/dvwa
        state: started
        restart: yes
        restart_policy: always
        ports:
          # Publish container port 80 as host port 80
          - "80:80"
        container_default_behavior: compatibility

    - name: Make sure docker service is started
      systemd:
        enabled: yes
        name: docker

    - name: Download and install Filebeat
      apt:
        deb: https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.6.2-amd64.deb
        state: present

    - name: Copy the Filebeat config file to the ElkVM
      copy:
        src: /etc/ansible/roles/files/filebeat-config.yml
        dest: /etc/filebeat/filebeat.yml

    - name: Enable Filebeat modules
      command: filebeat modules enable system

    - name: Filebeat setup
      command: filebeat setup

    - name: Start Filebeat
      command: service filebeat start

    - name: Enable Filebeat service on boot
      systemd:
        name: filebeat
        enabled: yes

    - name: Download and install Metricbeat
      apt:
        deb: https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.6.2-amd64.deb
        state: present

    - name: Copy the Metricbeat config file to the ElkVM
      copy:
        src: /etc/ansible/roles/files/metricbeat-config.yml
        dest: /etc/metricbeat/metricbeat.yml

    - name: Enable Metricbeat modules
      command: metricbeat modules enable docker

    - name: Metricbeat setup
      command: metricbeat setup

    - name: Start Metricbeat
      command: service metricbeat start

    - name: Enable Filebeat service on boot
      systemd:
        name: metricbeat
        enabled: yes