---
  - name: Elk VM Playbook
    hosts: elk
    become: true
    tasks:

    - name: More memory on VM
      sysctl:
        name: vm.max_map_count
        value: 262144

    - name: Install docker.io
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Install python3
      apt:
        name: python3-pip
        state: present

    - name: Install docker python package
      pip:
        name: docker

    - name: Configure a sebp/elk container
      docker_container:
        name: elk_container
        image: sebp/elk:761
        state: started
        restart: yes
        restart_policy: always
        ports:
          - "5601:5601"
          - "9200:9200"
          - "5044:5044"
        container_default_behavior: compatibility

    - name: Make sure docker service is started
      systemd:
        enabled: yes
        name: docker
