---
  - name: Playbook to install & configure Filebeat
    hosts: webservers
    become: true
    tasks:

#    - name: Download the Filebeat installation file
#      command:
#        cmd: curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.6.2-amd64.deb
#        creates: filebeat-7.6.2-amd64.deb

#    - name: Install Filebeat
#      command: sudo dpkg -i filebeat-7.6.2-amd64.deb

    - name: Download and install Filebeat
      apt:
        deb: https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.6.2-amd64.deb
        state: present

    - name: Copy the Filebeat config file to the ElkVM
      copy:
        src: /etc/ansible/roles/files/filebeat-config.yml
        dest: /etc/filebeat/filebeat.yml

    - name: Enable Filebeat modules
      command: filebeat modules enable system

    - name: Filebeat setup
      command: filebeat setup

#    - name: Log to stderr and disable syslog/file output
#      command: filebeat -e

    - name: Start Filebeat
      command: service filebeat start

    - name: Enable Filebeat service on boot
      systemd:
        name: filebeat
        enabled: yes
