---
  - name: Azure WebVM Playbook
    hosts: webservers
    become: true
    tasks:

    - name: Install docker.io
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Install python3
      apt:
        name: python3-pip
        state: present

    - name: Install docker python package
      pip:
        name: docker

    - name: Configure a DVWA container
      docker_container:
        name: dvwa_container
        image: cyberxsecurity/dvwa
        state: started
        restart: yes
        restart_policy: always
        ports:
          # Publish container port 80 as host port 80
          - "80:80"
        container_default_behavior: compatibility

    - name: Make sure docker service is started
      systemd:
        enabled: yes
        name: docker
